### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by jrochkind** [dandorman/rack_request_blocker#1]
You don't seem to have ever released this?

```
gem install rack_request_blocker
ERROR:  Could not find a valid gem 'rack_request_blocker' (>= 0) in any repository
```

Are you going to?

I'm interested in trying it as a solution. Wrote about the problems with feature test race conditions here. https://bibwild.wordpress.com/2016/02/18/struggling-towards-reliable-capybara-javascript-testing/ 
Your gem-ification of Joel Turkel's code is useful... if you release it?

**Comment by jrochkind** [comment]
Nevermind, I think this is kind of unfinished anyway. I see you haven't actually claimed the gem name on rubygems, so I might?

**Comment by dandorman** [comment]
Sorry I never responded to this! I see you took it and ran with it, and that's totally cool.
